name: 部署到github pages
on: push

jobs:
  npm-build:
    name: npm-build工作
    runs-on: ubuntu-latest

    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4

      - name: 切换到Frontend目录
        run: cd Frontend

      - name: 安装依赖
        run: npm install
          npm run build

      - name: 部署到github pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
